services:
  - type: web
    name: nab-api
    runtime: docker
    plan: free
    dockerfilePath: ./docker/api.Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: WEB_PUBLIC_URL
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: AI_MOCK
        value: 'true'
      - key: SENTRY_DSN
        sync: false
  - type: web
    name: nab-workers
    runtime: docker
    plan: free
    dockerfilePath: ./docker/workers.Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: WEB_PUBLIC_URL
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: VOYAGE_API_KEY
        sync: false
      - key: AI_MOCK
        value: 'true'
      - key: GREENHOUSE_BOARDS
        sync: false
      - key: INGEST_MOCK
        value: 'true'
      - key: SENTRY_DSN
        sync: false
